FROM perl:5.36

RUN apt-get update && apt-get install -y \
    mariadb-client \
    libdbi-perl \
    libdbd-mysql-perl \
    cron \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/psychostats

COPY ./psychostats/parser/run.sh /usr/local/bin/psychostats-parser
RUN chmod +x /usr/local/bin/psychostats-parser

CMD ["/usr/local/bin/psychostats-parser"]
